eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: Custmer
  datasource:
    url: jdbc:postgresql://localhost:5432/restuarantList-db
    password: ranjan
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect